Add bottom navigation bar
coffee-is-power/tabnews-mobile pull request #1
Opened 2022-07-25 19:48 UTC by thisiscleverson

Hi, in this pull request I added the Bottom Navigation Bar. I'm still working on it, but I'd like to share to see if you approve of the bottom navigation bar idea so I can continue working on it.

2022-07-25 22:54 UTC, coffee-is-power commented
Muito obrigado pela contribuição!
Eu gostei da ideia, falta algumas features que tem na navbar, mas eventualmente eu vou implementar essas coisas.
Como é um Work in Progress, coloquei o PR como draft

2022-07-26 11:07 UTC, thisiscleverson commented
Bom, então eu vou continuar os estudos com Flutter para poder ajudar esse projeto.

2022-07-26 15:00 UTC, coffee-is-power commented
Vai arrumar essas coisas?

2022-07-26 15:04 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +      //body: const PostList(),
Deixar codigo comentado assim deixa o codigo sujo

2022-07-26 15:17 UTC, coffee-is-power requested changes

2022-07-26 15:17 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +      backgroundColor: Color.fromARGB(255, 33, 35, 36),
```suggestion
```
Colocar uma cor exata assim pode gerar algumas inconsistencias na interface, o melhor é SEMPRE setar no tema

2022-07-26 23:59 UTC, coffee-is-power reviewed
Tem algumas coisinhas mas facilmente entra na master

2022-07-26 23:59 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
```suggestion
          BottomNavigationBarItem(
            icon: Icon(Icons.create),
            label: 'Write',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Search',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.more_vert),
            label: 'Settings',
          ),
```
Os nomes dos itens da navigation bar devem começar com letra maiuscula

2022-07-26 23:59 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +      //body: const PostList(),
```suggestion
```
Remove esse comentario
Deixar codigo comentado deixa o codigo sujo

2022-07-26 23:59 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
Acho que ter uma aba pra criar conteudo é um pouco estranho, é melhor ter um floating button, fica mais bonito

2022-07-27 00:04 UTC, coffee-is-power requested changes

2022-07-27 00:04 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +      backgroundColor: Color.fromARGB(255, 33, 35, 36),
```suggestion
```
Colocar uma cor exata assim pode gerar algumas inconsistencias na interface, o melhor é SEMPRE setar no tema

2022-07-27 00:04 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
Acho que ter uma aba pra criar conteudo é um pouco estranho, é melhor ter um floating button, fica mais bonito

2022-07-27 00:04 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
```suggestion
          BottomNavigationBarItem(
            icon: Icon(Icons.create),
            label: 'Write',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Search',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.more_vert),
            label: 'Settings',
          ),
```
Os nomes dos itens da navigation bar devem começar com letra maiuscula

2022-07-27 00:04 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +      //body: const PostList(),
```suggestion
```
Remove esse comentario
Deixar codigo comentado deixa o codigo sujo

2022-07-27 22:10 UTC, thisiscleverson commented
eu pensei isso no inicio

2022-07-27 22:11 UTC, thisiscleverson commented on lib/widget/screens/home.dart
> +          ),
eu pensei isso no inicio.

2022-07-27 22:21 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
Você pode reverter essa alteração?

2022-07-29 09:10 UTC, thisiscleverson commented on lib/widget/screens/home.dart
> +          ),
como ?

2022-07-29 11:50 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
Adiciona o floating action button denovo

2022-07-29 14:34 UTC, thisiscleverson commented on lib/widget/screens/home.dart
> +          ),
> Sim, temo eu fazer isso!

2022-07-29 15:38 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
Eu vou commitar na sua branch, se me dá licença.

2022-07-29 15:42 UTC, coffee-is-power commented on lib/widget/screens/home.dart
> +          ),
Pronto, já resolvi o problema no commit 171087b

2022-07-29 15:42 UTC, coffee-is-power commented
Acho que agora ta pronto para mergear! Muito obrigado pelo PR!

2022-07-29 15:43 UTC, merged